/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Checkout as PrismaCheckout,
  Cart as PrismaCart,
} from "@prisma/client";

export class CheckoutServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CheckoutCountArgs, "select">): Promise<number> {
    return this.prisma.checkout.count(args);
  }

  async checkouts(
    args: Prisma.CheckoutFindManyArgs
  ): Promise<PrismaCheckout[]> {
    return this.prisma.checkout.findMany(args);
  }
  async checkout(
    args: Prisma.CheckoutFindUniqueArgs
  ): Promise<PrismaCheckout | null> {
    return this.prisma.checkout.findUnique(args);
  }
  async createCheckout(
    args: Prisma.CheckoutCreateArgs
  ): Promise<PrismaCheckout> {
    return this.prisma.checkout.create(args);
  }
  async updateCheckout(
    args: Prisma.CheckoutUpdateArgs
  ): Promise<PrismaCheckout> {
    return this.prisma.checkout.update(args);
  }
  async deleteCheckout(
    args: Prisma.CheckoutDeleteArgs
  ): Promise<PrismaCheckout> {
    return this.prisma.checkout.delete(args);
  }

  async getCart(parentId: string): Promise<PrismaCart | null> {
    return this.prisma.checkout
      .findUnique({
        where: { id: parentId },
      })
      .cart();
  }
}
